### ISSUE TITLE
Gridlines enhancement request

### ISSUE THREAD

**Issue by hvdm** [TurboPack/MustangpeakEasyListview#17]
Is it possible to have gridlines with options (like TVirtualStringTree).
It should be nice if you can have full vertical gridlines only

**Comment by romankassebaum** [comment]
Maybe you can do this and send me a pull request.

**Comment by hvdm** [comment]
Ill try but I am just a hobby developer :-)

**Comment by hvdm** [comment]
Changed the gridline a little bit so that it reaches the bottom of the LV
