### ISSUE TITLE
Issue with Delphi 12

### ISSUE THREAD

**Issue by mhietan** [TurboPack/MustangpeakEasyListview#20]
Using Delphi 12 and Win64 build:
```
function TEasyHeader.GetViewWidth: Integer;
   
			 
begin
  if Positions.Count > 0 then
			   
    Result := Positions[Positions.Count - 1].DisplayRect.Right
  else
    Result := 0
end;
```
Compiler error occurs in line Result := Positions[Positions.Count - 1].DisplayRect.Right
Win32 compile is successful.

**Comment by romankassebaum** [comment]
It seems to be an issue with the 64 bit compiler. I fixed it with a local variable.
