### ISSUE TITLE
Bug in TEasyGridGroup.AdjacentItem

### ISSUE THREAD

**Issue by ErwinDenissen** [TurboPack/MustangpeakEasyListview#22]
Better use BoundsRect, as we can't rely on LabelRect when HideCaption = True.

       if Assigned(LastItem) then
       begin
         LastItem.View.ItemRectArray(LastItem, nil, nil, Item.Caption, RectArray);
         // Bug fix, LabelRect -> BoundsRect as LabelRect is (0, 0, 0, 0) if HideCaption = True       
         if TestPt.Y > RectArray.BoundsRect.Bottom - 1 then
           TestPt.Y := RectArray.BoundsRect.Bottom - 1;
       end;

**Comment by romankassebaum** [comment]
Fixed.
